[build]
  # Comando que o Netlify vai rodar para compilar seu projeto
  command = "npm run build"
  # Pasta que contém os arquivos finais minificados (HTML, CSS e JS)
  publish = "dist"

# Redirecionamento padrão para garantir o funcionamento do roteamento interno (se usar Vue Router, etc)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200